version: '3'
services:
  mysql56:
    image: mysql:5.6
    volumes:
      - ./docker/development/etc/mysql/conf.d:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  development:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/lib/docker/home:/home
    depends_on:
      - mysql56
