version: '3'
services:
  mysql56:
    image: mysql:5.6
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  development:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ~/.ssh:/home/orangevtr/.ssh
      - ./data/workspace:/home/orangevtr/workspace
    depends_on:
      - mysql56
    ports:
      - "3000:3000"
      - "5000:5000"
      - "8080:8080"
      - "2222:22"
    links:
      - mysql56
